version: 2

sources:
  - name: gz_raw_data
    schema: gz_raw_data
    description: "Raw GZ veri kümesi - satış, ürün, gönderim ve reklam kampanya tablolarını içerir"
    tables:
      - name: raw_gz_sales
        description: "Ham satış verileri"
        columns:
          - name: date_date
            description: "Date of the sale"
          - name: orders_id
            description: "Unique identifier for each order"
          - name: pdt_id
            description: "Unique identifier for each product"
          - name: revenue
            description: "Revenue of the sale"
          - name: quantity
            description: "Quantity of the sales"
        config:
          freshness:
            warn_after: {count: 90, period: day}
            error_after: {count: 120, period: day}
          loaded_at_field: date_date

      - name: raw_gz_product
        description: "Ham ürün bilgileri"
        columns:
          - name: products_id
            description: "Unique identifier for each product"
            tests:
              - not_null
              - unique
          - name: purchSE_PRICE
            description: "Purchasing price of the product"

      - name: raw_gz_ship
        description: "Ham gönderim bilgileri"
        columns:
          - name: orders_id
            description: "Unique shipment identifier"
            tests:
              - not_null
              - unique
          - name: shipping_fee
            description: "Shipping Fee"
          - name: log_cost
            description: "Log cost"
          - name: ship_cost
            description: "Shipment cost"

      - name: raw_gz_adwords
        description: "Google Ads raw campaign performance data"
        columns:
          - name: date_date
            description: "Date of the campaign data record"
            tests:
              - not_null
          - name: paid_source
            description: "Marketing source (e.g., 'google_ads')"
            tests:
              - not_null
          - name: campaign_key
            description: "Unique identifier of the campaign"
            tests:
              - not_null
          - name: camPGN_name
            description: "Name of the campaign"
          - name: ads_cost
            description: "Total advertising cost (in local currency)"
            tests:
              - not_null
          - name: impression
            description: "Number of times the ad was displayed (impressions)"
            tests:
              - not_null
          - name: click
            description: "Number of times the ad was clicked"
            tests:
              - not_null

      - name: raw_gz_bing
        description: "Microsoft Bing Ads raw campaign performance data"
        columns:
          - name: date_date
            description: "Date of the campaign data record"
            tests:
              - not_null
          - name: paid_source
            description: "Marketing source (e.g., 'bing_ads')"
            tests:
              - not_null
          - name: campaign_key
            description: "Unique identifier of the campaign"
            tests:
              - not_null
          - name: camPGN_name
            description: "Name of the campaign"
          - name: ads_cost
            description: "Total advertising cost (in local currency)"
            tests:
              - not_null
          - name: impression
            description: "Number of times the ad was displayed (impressions)"
            tests:
              - not_null
          - name: click
            description: "Number of times the ad was clicked"
            tests:
              - not_null

      - name: raw_gz_criteo
        description: "Criteo Ads raw campaign performance data"
        columns:
          - name: date_date
            description: "Date of the campaign data record"
            tests:
              - not_null
          - name: paid_source
            description: "Marketing source (e.g., 'criteo')"
            tests:
              - not_null
          - name: campaign_key
            description: "Unique identifier of the campaign"
            tests:
              - not_null
          - name: camPGN_name
            description: "Name of the campaign"
          - name: ads_cost
            description: "Total advertising cost (in local currency)"
            tests:
              - not_null
          - name: impression
            description: "Number of times the ad was displayed (impressions)"
            tests:
              - not_null
          - name: click
            description: "Number of times the ad was clicked"
            tests:
              - not_null

      - name: raw_gz_facebook
        description: "Meta (Facebook & Instagram) Ads raw campaign performance data"
        columns:
          - name: date_date
            description: "Date of the campaign data record"
            tests:
              - not_null
          - name: paid_source
            description: "Marketing source (e.g., 'facebook_ads')"
            tests:
              - not_null
          - name: campaign_key
            description: "Unique identifier of the campaign"
            tests:
              - not_null
          - name: camPGN_name
            description: "Name of the campaign"
          - name: ads_cost
            description: "Total advertising cost (in local currency)"
            tests:
              - not_null
          - name: impression
            description: "Number of times the ad was displayed (impressions)"
            tests:
              - not_null
          - name: click
            description: "Number of times the ad was clicked"
            tests:
              - not_null
